import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='max-w-7xl m-auto'>
          <div className='flex justify-center'>
<<<<<<< HEAD
            <Navbar className="z-90 " />
=======
            <Navbar />
>>>>>>> 574091bd4e829d169cc54d7392e62471ae4e64f9
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
